version: "3.9"
services:
  api:
    image: ghcr.io/otomad-database/otomad-database/api:latest
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
      neo4j:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://user:pass@postgres:5432/test"
      NEO4J_URL: "bolt://neo4j:7687"
      NEO4J_USERNAME: "neo4j"
      NEO4J_PASSWORD: "password"
    ports:
      - target: 8080
        published: 4000
  migration:
    image: ghcr.io/otomad-database/otomad-database/api-migration:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://user:pass@postgres:5432/test"
  postgres:
    image: postgres:15
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
  neo4j:
    image: neo4j:5.2
    environment:
      NEO4J_AUTH: neo4j/password
    healthcheck:
      test: neo4j status || exit 1 # TODO:
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - type: volume
        source: neo4j_data
        target: /data
      - type: volume
        source: neo4j_logs
        target: /logs
volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
