apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.10/manifests/install.yaml
  - ./ingress.yaml
patchesStrategicMerge:
  - argocd-cm/kustomize.patch.yaml
  - argocd-repo-server/ksops.patch.yaml
