name: NixOS

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  remilia:
    name: NixOS(remilia)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
      - uses: cachix/cachix-action@v12
        with:
          name: sno2wman
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build ".#nixosConfigurations.remilia.config.system.build.toplevel" -L
